export type PermissionCatalogKind = 'base-toggle' | 'menu' | 'action';

export interface FeaturePermissionCatalogItem {
  key: string;
  kind: PermissionCatalogKind;
  label: string;
  frontendEntrances: string[];
  backendExecutionPoints: string[];
  auditEventType: 'ACCESS_ACTION_DENIED' | 'ACCESS_MENU_DENIED' | 'ACCESS_CHANNEL_DENIED';
}

/**
 * 统一登记权限中心可配置的权限点，供后端执行收口、测试覆盖和文档输出复用。
 */
export const FEATURE_PERMISSION_CATALOG: FeaturePermissionCatalogItem[] = [
  {
    key: 'status',
    kind: 'base-toggle',
    label: '状态',
    frontendEntrances: ['权限中心角色权限抽屉'],
    backendExecutionPoints: ['AccessDecisionService.resolveRolePermissions'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'webConsoleEnabled',
    kind: 'base-toggle',
    label: 'Web 入口',
    frontendEntrances: ['登录后应用壳层导航', 'Web 路由守卫'],
    backendExecutionPoints: ['AccessDecisionService.buildDecision(web-console)'],
    auditEventType: 'ACCESS_CHANNEL_DENIED',
  },
  {
    key: 'wecomBotEligible',
    kind: 'base-toggle',
    label: '企微入口资格',
    frontendEntrances: ['权限中心预览'],
    backendExecutionPoints: ['AccessDecisionService.buildDecision(wecom-bot)'],
    auditEventType: 'ACCESS_CHANNEL_DENIED',
  },
  {
    key: 'exportAllowed',
    kind: 'base-toggle',
    label: '导出权限',
    frontendEntrances: ['分析工作台导出按钮', '结果详情导出按钮'],
    backendExecutionPoints: ['ExportPolicyService.evaluate'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'templateManageAllowed',
    kind: 'base-toggle',
    label: '模板治理',
    frontendEntrances: ['查询模板治理页'],
    backendExecutionPoints: ['QueryTemplateService.ensureTemplateManageAccess'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'contractReviewUploadAllowed',
    kind: 'base-toggle',
    label: '合同上传',
    frontendEntrances: ['合同审核工作台上传入口'],
    backendExecutionPoints: ['ContractReviewService.createTask'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'contractReviewCrossViewAllowed',
    kind: 'base-toggle',
    label: '查看他人合同',
    frontendEntrances: ['合同审核任务详情页'],
    backendExecutionPoints: ['ContractReviewService.getTaskDetail'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'contractReviewCrossDownloadAllowed',
    kind: 'base-toggle',
    label: '下载他人产物',
    frontendEntrances: ['合同审核产物下载按钮'],
    backendExecutionPoints: ['ContractReviewService.getArtifactDownload'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'analysis-workbench',
    kind: 'menu',
    label: '智能分析',
    frontendEntrances: ['/analysis', '/analysis/results/:queryId'],
    backendExecutionPoints: ['AnalysisService.createQuery', 'AnalysisService.getQuery'],
    auditEventType: 'ACCESS_MENU_DENIED',
  },
  {
    key: 'contract-review',
    kind: 'menu',
    label: '智能合同审核',
    frontendEntrances: ['/contract-review', '/contract-review/tasks/:taskId'],
    backendExecutionPoints: ['ContractReviewService.listRecentTasks', 'ContractReviewService.getTaskDetail'],
    auditEventType: 'ACCESS_MENU_DENIED',
  },
  {
    key: 'management-report',
    kind: 'menu',
    label: '经营报表',
    frontendEntrances: ['/management-report'],
    backendExecutionPoints: ['ManagementReportService.getOptions', 'ManagementReportService.createSnapshot'],
    auditEventType: 'ACCESS_MENU_DENIED',
  },
  {
    key: 'permission-center',
    kind: 'menu',
    label: '权限中心',
    frontendEntrances: ['/governance/access'],
    backendExecutionPoints: ['AccessGovernanceController'],
    auditEventType: 'ACCESS_MENU_DENIED',
  },
  {
    key: 'connection-policy',
    kind: 'menu',
    label: '连接策略',
    frontendEntrances: ['/governance/connections'],
    backendExecutionPoints: ['GovernanceService'],
    auditEventType: 'ACCESS_MENU_DENIED',
  },
  {
    key: 'audit-center',
    kind: 'menu',
    label: '审计中心',
    frontendEntrances: ['/audit'],
    backendExecutionPoints: ['AuditController.listAuditEvents'],
    auditEventType: 'ACCESS_MENU_DENIED',
  },
  {
    key: 'ai-model-governance',
    kind: 'menu',
    label: 'AI配置',
    frontendEntrances: ['/governance/ai-models'],
    backendExecutionPoints: ['AiModelGovernanceController'],
    auditEventType: 'ACCESS_MENU_DENIED',
  },
  {
    key: 'analysis.use',
    kind: 'action',
    label: '分析问数',
    frontendEntrances: ['分析工作台提交按钮'],
    backendExecutionPoints: ['AnalysisService.createQuery'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'analysis.follow_up',
    kind: 'action',
    label: '继续追问',
    frontendEntrances: ['结果详情页追问按钮'],
    backendExecutionPoints: ['AnalysisService.createQuery(follow-up)'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'analysis.export',
    kind: 'action',
    label: '导出结果',
    frontendEntrances: ['分析工作台导出按钮', '结果详情导出按钮'],
    backendExecutionPoints: ['ExportService.createExport'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'management.report.view',
    kind: 'action',
    label: '查看经营报表',
    frontendEntrances: ['/management-report'],
    backendExecutionPoints: [
      'ManagementReportService.getOptions',
      'ManagementReportService.createSnapshot',
      'ManagementReportService.getSectionDetail',
    ],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'management.report.export',
    kind: 'action',
    label: '导出经营报表',
    frontendEntrances: ['/management-report 导出按钮'],
    backendExecutionPoints: ['ManagementReportService.exportReport'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'template.view',
    kind: 'action',
    label: '模板可见',
    frontendEntrances: ['分析工作台常用查询面板'],
    backendExecutionPoints: ['QueryTemplateService.listVisible'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'template.manage',
    kind: 'action',
    label: '模板治理',
    frontendEntrances: ['智能分析页查询模板管理入口'],
    backendExecutionPoints: ['QueryTemplateAdminController'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'template.sql.write',
    kind: 'action',
    label: '查询模板 SQL 编写',
    frontendEntrances: ['智能分析页查询模板新增、校验、预览和保存入口'],
    backendExecutionPoints: [
      'QueryTemplateService.create',
      'QueryTemplateService.update',
      'QueryTemplateAdminController.validateGovernanceTemplate',
      'QueryTemplateAdminController.previewGovernanceTemplate',
    ],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'wecom.analysis.use',
    kind: 'action',
    label: '企业微信问数',
    frontendEntrances: ['企业微信机器人分析入口'],
    backendExecutionPoints: ['AnalysisService.createQuery(wecom-bot)'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'wecom.customer.create',
    kind: 'action',
    label: '企业微信新增客户',
    frontendEntrances: ['企业微信新增客户入口'],
    backendExecutionPoints: ['CustomerCreateController', 'WecomBotService.handleCustomerCreateFlow'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'wecom.opportunity.create',
    kind: 'action',
    label: '企业微信新增商机',
    frontendEntrances: ['企业微信新增商机入口'],
    backendExecutionPoints: ['OpportunityCreateController', 'WecomBotService.handleOpportunityCreateFlow'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'wecom.followup.writeback',
    kind: 'action',
    label: '企业微信跟进写回',
    frontendEntrances: ['企业微信跟进草稿与确认链路'],
    backendExecutionPoints: ['WecomBotService.dispatchFollowUpTemplateWritebackConfirmation', 'WecomBotService.executeFollowUpWriteback'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'wecom.daily_report.preview',
    kind: 'action',
    label: '日报预览',
    frontendEntrances: ['企业微信个人日报预览', '企业微信团队日报预览'],
    backendExecutionPoints: ['WecomBotService.handleDailyReportPreviewQuery', 'WecomBotService.handleTeamDailyReportPreviewQuery'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'governance.policy.manage',
    kind: 'action',
    label: '系统级治理',
    frontendEntrances: ['/governance/access', '/governance/connections'],
    backendExecutionPoints: [
      'GovernanceService',
      'AccessGovernanceService',
      'AccessGovernanceService.listDailyReportDepartments',
      'AccessGovernanceService.updateDailyReportDepartmentPolicy',
      'AccessGovernanceService.previewDailyReportDelivery',
    ],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'audit.view',
    kind: 'action',
    label: '查看审计',
    frontendEntrances: ['/audit'],
    backendExecutionPoints: ['AuditController.listAuditEvents'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'audit.sql.view',
    kind: 'action',
    label: '查看 SQL 审计',
    frontendEntrances: ['/audit SQL 审计 Tab'],
    backendExecutionPoints: [
      'SqlAuditController.getSummary',
      'SqlAuditController.listSqlAudits',
      'SqlAuditController.getSqlAuditDetail',
    ],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'audit.sql.view_sensitive',
    kind: 'action',
    label: '查看 SQL 敏感明细',
    frontendEntrances: ['/audit SQL 审计 reveal 按钮'],
    backendExecutionPoints: ['SqlAuditController.revealSqlAudit'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'ai_profile.manage',
    kind: 'action',
    label: 'AI配置治理',
    frontendEntrances: ['/governance/ai-models'],
    backendExecutionPoints: ['AiModelGovernanceController'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'contract.review.upload',
    kind: 'action',
    label: '合同上传',
    frontendEntrances: ['/contract-review'],
    backendExecutionPoints: ['ContractReviewService.createTask'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'contract.review.cross_view',
    kind: 'action',
    label: '查看他人合同',
    frontendEntrances: ['/contract-review/tasks/:taskId'],
    backendExecutionPoints: ['ContractReviewService.getTaskDetail'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
  {
    key: 'contract.review.cross_download',
    kind: 'action',
    label: '下载他人产物',
    frontendEntrances: ['/contract-review/tasks/:taskId/artifacts/:artifactId/download'],
    backendExecutionPoints: ['ContractReviewService.getArtifactDownload'],
    auditEventType: 'ACCESS_ACTION_DENIED',
  },
];

export const FEATURE_PERMISSION_KEYS = FEATURE_PERMISSION_CATALOG.map((item) => item.key);
