import type { ManagementMetricDefinition } from './management-report.types';

export const MANAGEMENT_REPORT_METRIC_DICTIONARY: Record<
  string,
  ManagementMetricDefinition
> = {
  leadCount: {
    key: 'leadCount',
    label: '新增线索',
    sourceTables: ['leads'],
    sourceFields: ['id', 'created_at'],
    timeField: 'leads.created_at',
    aggregation: 'count',
    description: '统计筛选期内创建的线索数量。',
  },
  customerCount: {
    key: 'customerCount',
    label: '新增客户',
    sourceTables: ['customers'],
    sourceFields: ['id', 'created_at'],
    timeField: 'customers.created_at',
    aggregation: 'count',
    description: '统计筛选期内创建的客户数量。',
  },
  opportunityAmount: {
    key: 'opportunityAmount',
    label: '商机金额',
    sourceTables: ['opportunities'],
    sourceFields: ['amount', 'get_time', 'created_at'],
    timeField: 'COALESCE(opportunities.get_time, opportunities.created_at)',
    aggregation: 'sum',
    description: '统计筛选期内商机金额汇总。',
  },
  contractAmount: {
    key: 'contractAmount',
    label: '有效收入',
    sourceTables: ['contracts', 'contract_assets'],
    sourceFields: ['numeric_asset_7ee237', 'sign_date', 'created_at'],
    timeField: 'COALESCE(contracts.sign_date, contracts.created_at)',
    aggregation: 'sum',
    description: '统计筛选期内合同有效收入汇总。',
  },
  receivedAmount: {
    key: 'receivedAmount',
    label: '期内回款',
    sourceTables: ['received_payments'],
    sourceFields: ['amount', 'receive_date'],
    timeField: 'received_payments.receive_date',
    aggregation: 'sum',
    description: '统计筛选期内实际回款金额。',
  },
  overdueAmount: {
    key: 'overdueAmount',
    label: '逾期应收',
    sourceTables: ['received_payment_plans'],
    sourceFields: ['amount', 'receive_date', 'status'],
    timeField: 'received_payment_plans.receive_date',
    aggregation: 'sum',
    description: '统计截至结束日仍处于逾期状态的应收计划金额。',
  },
  leadConversionRate: {
    key: 'leadConversionRate',
    label: '线索转客户率',
    sourceTables: ['leads'],
    sourceFields: ['id', 'converted_customer_at'],
    timeField: 'leads.created_at',
    aggregation: 'ratio',
    formula: '转客户线索数 / cohort 线索数',
    description: '使用 cohort 线索作为分母，统计截至 endDate 的转客户率。',
  },
  customerActivationRate: {
    key: 'customerActivationRate',
    label: '客户激活率',
    sourceTables: ['customers'],
    sourceFields: ['id', 'active_since'],
    timeField: 'customers.created_at <= endDate',
    aggregation: 'ratio',
    formula: '活跃客户数 / 客户池总数',
    description: '按期末客户池统计激活客户占比。',
  },
  riskOpportunityCount: {
    key: 'riskOpportunityCount',
    label: '风险商机数',
    sourceTables: ['opportunities'],
    sourceFields: ['id', 'expect_sign_date', 'revisit_at', 'stage_updated_at'],
    timeField: 'COALESCE(opportunities.get_time, opportunities.created_at) <= endDate',
    aggregation: 'count',
    description: '统计截至结束日存在超期、久未跟进等风险信号的商机数量。',
  },
  acceptancePendingAmount: {
    key: 'acceptancePendingAmount',
    label: '待验收金额',
    sourceTables: ['contracts', 'contract_assets'],
    sourceFields: ['numeric_asset_7ee237', 'accepted_at'],
    timeField: 'COALESCE(contracts.sign_date, contracts.created_at)',
    aggregation: 'sum',
    description: '统计签约后仍未完成验收的合同有效收入。',
  },
};

export const MANAGEMENT_REPORT_SECTION_METRIC_KEYS: Record<string, string[]> = {
  overview: [
    'leadCount',
    'customerCount',
    'opportunityAmount',
    'contractAmount',
    'receivedAmount',
    'riskOpportunityCount',
  ],
  'executive-summary': [
    'receivedAmount',
    'overdueAmount',
    'leadConversionRate',
    'customerActivationRate',
  ],
  regional: ['opportunityAmount'],
  leads: ['leadCount'],
  'lead-conversion': ['leadConversionRate'],
  'lead-opportunity': ['leadCount'],
  opportunities: ['opportunityAmount', 'riskOpportunityCount'],
  customers: ['customerCount', 'customerActivationRate'],
  acceptance: ['contractAmount', 'acceptancePendingAmount'],
  collections: ['receivedAmount', 'overdueAmount'],
  risks: ['riskOpportunityCount', 'overdueAmount'],
};
