export interface ManagementReportDepartmentDefinition {
  id: string;
  label: string;
  parentId?: string;
}

export interface ManagementReportLeadRecord {
  id: string;
  departmentId: string;
  companyName: string;
  ownerName: string;
  source: string;
  followUpStatus: '待处理' | '持续跟进' | '已转客户' | '已转商机' | '关闭';
  qualityLevel: '高质量' | '中质量' | '待培育' | '风险';
  demandTag: string;
  responseHours: number;
  customerRole: '最终客户' | '代理商' | '集成商';
  createdAt: string;
  convertedCustomerAt?: string;
  convertedOpportunityAt?: string;
  wonAt?: string;
  riskFlag: boolean;
}

export interface ManagementReportCustomerRecord {
  id: string;
  departmentId: string;
  name: string;
  ownerName: string;
  level: string;
  city: string;
  region: string;
  industry: string;
  createdAt: string;
  activeSince?: string;
  hasOpportunity: boolean;
  followUpStatus: '初次联络' | '持续推进' | '停滞观察';
  historyDeal: boolean;
  lifecycleStage: '新客户' | '激活池' | '深耕池' | '预警池';
}

export interface ManagementReportOpportunityRecord {
  id: string;
  departmentId: string;
  ownerName: string;
  customerName: string;
  region: string;
  city: string;
  industry: string;
  amount: number;
  stage: string;
  source: string;
  agentName?: string;
  ecosystemType?: '核心伙伴' | '成长伙伴' | '沉睡伙伴';
  productSolution: string;
  industrySolution: string;
  promised: boolean;
  createdAt: string;
  getTime?: string;
  expectSignDate?: string;
  revisitAt?: string;
  stageUpdatedAt?: string;
}

export interface ManagementReportContractRecord {
  id: string;
  departmentId: string;
  customerName: string;
  ownerName: string;
  amount: number;
  createdAt: string;
  signDate?: string;
  acceptedAt?: string;
  expectedAcceptanceDate?: string;
}

export interface ManagementReportPaymentPlanRecord {
  id: string;
  contractId: string;
  amount: number;
  receiveDate: string;
  status: 'PLANNED' | 'RECEIVED' | 'OVERDUE';
}

export interface ManagementReportPaymentRecord {
  id: string;
  contractId: string;
  amount: number;
  receiveDate: string;
}

export const MANAGEMENT_REPORT_DEPARTMENTS: ManagementReportDepartmentDefinition[] = [
  { id: 'dept_sales', label: '销售部' },
  { id: 'dept_region_east', label: '华东销售部', parentId: 'dept_sales' },
  { id: 'dept_sales_management', label: '销售管理部' },
  { id: 'dept_product', label: '产品部' },
  { id: 'dept_admin', label: '行政管理部' },
];

export const MANAGEMENT_REPORT_LEADS: ManagementReportLeadRecord[] = [
  {
    id: 'lead_001',
    departmentId: 'dept_sales',
    companyName: '山东农信',
    ownerName: '李浩',
    source: '公开课',
    followUpStatus: '已转商机',
    qualityLevel: '高质量',
    demandTag: 'DLP',
    responseHours: 4,
    customerRole: '最终客户',
    createdAt: '2026-01-05',
    convertedCustomerAt: '2026-01-12',
    convertedOpportunityAt: '2026-01-20',
    riskFlag: false,
  },
  {
    id: 'lead_002',
    departmentId: 'dept_region_east',
    companyName: '杭州云计算',
    ownerName: '张琳',
    source: '转介绍',
    followUpStatus: '已转客户',
    qualityLevel: '高质量',
    demandTag: '终端准入',
    responseHours: 6,
    customerRole: '集成商',
    createdAt: '2026-01-18',
    convertedCustomerAt: '2026-02-08',
    convertedOpportunityAt: '2026-02-16',
    wonAt: '2026-03-10',
    riskFlag: false,
  },
  {
    id: 'lead_003',
    departmentId: 'dept_sales',
    companyName: '青岛零售集团',
    ownerName: '王敏',
    source: '官网',
    followUpStatus: '待处理',
    qualityLevel: '风险',
    demandTag: '桌面管理',
    responseHours: 72,
    customerRole: '最终客户',
    createdAt: '2026-02-03',
    riskFlag: true,
  },
  {
    id: 'lead_004',
    departmentId: 'dept_sales',
    companyName: '苏州制造',
    ownerName: '李浩',
    source: '活动',
    followUpStatus: '已转商机',
    qualityLevel: '中质量',
    demandTag: '终端安全',
    responseHours: 18,
    customerRole: '代理商',
    createdAt: '2026-02-20',
    convertedOpportunityAt: '2026-03-05',
    riskFlag: false,
  },
  {
    id: 'lead_005',
    departmentId: 'dept_region_east',
    companyName: '宁波仓储科技',
    ownerName: '张琳',
    source: '合作伙伴',
    followUpStatus: '持续跟进',
    qualityLevel: '待培育',
    demandTag: '文件交换',
    responseHours: 24,
    customerRole: '集成商',
    createdAt: '2026-03-02',
    riskFlag: true,
  },
  {
    id: 'lead_006',
    departmentId: 'dept_region_east',
    companyName: '联软科技集团',
    ownerName: '张琳',
    source: '转介绍',
    followUpStatus: '已转客户',
    qualityLevel: '高质量',
    demandTag: '研发数据加密',
    responseHours: 8,
    customerRole: '最终客户',
    createdAt: '2026-03-15',
    convertedCustomerAt: '2026-03-22',
    riskFlag: false,
  },
  {
    id: 'lead_007',
    departmentId: 'dept_sales',
    companyName: '广州光中科技',
    ownerName: '王敏',
    source: '搜索引擎',
    followUpStatus: '持续跟进',
    qualityLevel: '中质量',
    demandTag: '终端准入',
    responseHours: 12,
    customerRole: '最终客户',
    createdAt: '2026-03-08',
    convertedOpportunityAt: '2026-03-18',
    riskFlag: false,
  },
  {
    id: 'lead_008',
    departmentId: 'dept_sales',
    companyName: '广东腾原新材料',
    ownerName: '李浩',
    source: '渠道合作',
    followUpStatus: '关闭',
    qualityLevel: '风险',
    demandTag: 'NAC',
    responseHours: 96,
    customerRole: '代理商',
    createdAt: '2026-01-28',
    riskFlag: true,
  },
  {
    id: 'lead_009',
    departmentId: 'dept_sales',
    companyName: '山东农信',
    ownerName: '李浩',
    source: '活动',
    followUpStatus: '已转客户',
    qualityLevel: '高质量',
    demandTag: '零信任',
    responseHours: 10,
    customerRole: '最终客户',
    createdAt: '2026-02-14',
    convertedCustomerAt: '2026-02-20',
    convertedOpportunityAt: '2026-03-02',
    riskFlag: false,
  },
  {
    id: 'lead_010',
    departmentId: 'dept_region_east',
    companyName: '杭州云计算',
    ownerName: '张琳',
    source: '合作伙伴',
    followUpStatus: '持续跟进',
    qualityLevel: '中质量',
    demandTag: '文件交换',
    responseHours: 16,
    customerRole: '集成商',
    createdAt: '2026-02-28',
    riskFlag: false,
  },
  {
    id: 'lead_011',
    departmentId: 'dept_sales',
    companyName: '广州医联云',
    ownerName: '吴李斌',
    source: '合作伙伴',
    followUpStatus: '已转商机',
    qualityLevel: '高质量',
    demandTag: '终端准入',
    responseHours: 7,
    customerRole: '最终客户',
    createdAt: '2026-03-06',
    convertedCustomerAt: '2026-03-10',
    convertedOpportunityAt: '2026-03-14',
    riskFlag: false,
  },
  {
    id: 'lead_012',
    departmentId: 'dept_sales',
    companyName: '佛山智造装备',
    ownerName: '盛少梅',
    source: '渠道合作',
    followUpStatus: '已转客户',
    qualityLevel: '高质量',
    demandTag: 'DLP',
    responseHours: 9,
    customerRole: '代理商',
    createdAt: '2026-02-11',
    convertedCustomerAt: '2026-02-16',
    riskFlag: false,
  },
  {
    id: 'lead_013',
    departmentId: 'dept_region_east',
    companyName: '中山政务云平台',
    ownerName: '黄镇城',
    source: '搜索引擎',
    followUpStatus: '持续跟进',
    qualityLevel: '中质量',
    demandTag: '跨网文件交换',
    responseHours: 20,
    customerRole: '集成商',
    createdAt: '2026-03-04',
    convertedOpportunityAt: '2026-03-11',
    riskFlag: false,
  },
  {
    id: 'lead_014',
    departmentId: 'dept_sales',
    companyName: '东莞半导体研究院',
    ownerName: '蔡明宇',
    source: '转介绍',
    followUpStatus: '已转商机',
    qualityLevel: '高质量',
    demandTag: '研发数据加密',
    responseHours: 5,
    customerRole: '最终客户',
    createdAt: '2026-02-18',
    convertedCustomerAt: '2026-02-22',
    convertedOpportunityAt: '2026-02-27',
    riskFlag: false,
  },
  {
    id: 'lead_015',
    departmentId: 'dept_region_east',
    companyName: '海口文旅集团',
    ownerName: '梁俊达',
    source: '活动',
    followUpStatus: '待处理',
    qualityLevel: '待培育',
    demandTag: '移动办公安全',
    responseHours: 48,
    customerRole: '最终客户',
    createdAt: '2026-03-18',
    riskFlag: true,
  },
];

export const MANAGEMENT_REPORT_CUSTOMERS: ManagementReportCustomerRecord[] = [
  {
    id: 'customer_001',
    departmentId: 'dept_sales',
    name: '山东农信',
    ownerName: '李浩',
    level: '重点客户',
    city: '济南',
    region: '华北',
    industry: '金融',
    createdAt: '2026-01-12',
    activeSince: '2026-02-01',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: true,
    lifecycleStage: '深耕池',
  },
  {
    id: 'customer_002',
    departmentId: 'dept_region_east',
    name: '苏州制造',
    ownerName: '张琳',
    level: '战略客户',
    city: '苏州',
    region: '华东',
    industry: '制造',
    createdAt: '2026-02-08',
    activeSince: '2026-03-01',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: false,
    lifecycleStage: '激活池',
  },
  {
    id: 'customer_003',
    departmentId: 'dept_sales',
    name: '青岛零售集团',
    ownerName: '王敏',
    level: '标准客户',
    city: '青岛',
    region: '华北',
    industry: '零售',
    createdAt: '2026-03-04',
    hasOpportunity: false,
    followUpStatus: '初次联络',
    historyDeal: false,
    lifecycleStage: '预警池',
  },
  {
    id: 'customer_004',
    departmentId: 'dept_region_east',
    name: '杭州云计算',
    ownerName: '张琳',
    level: '重点客户',
    city: '杭州',
    region: '华东',
    industry: '互联网',
    createdAt: '2025-12-18',
    activeSince: '2026-01-15',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: true,
    lifecycleStage: '深耕池',
  },
  {
    id: 'customer_005',
    departmentId: 'dept_sales',
    name: '广州光中科技',
    ownerName: '王敏',
    level: '潜力客户',
    city: '广州',
    region: '华南',
    industry: '制造',
    createdAt: '2026-03-12',
    activeSince: '2026-03-18',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: false,
    lifecycleStage: '激活池',
  },
  {
    id: 'customer_006',
    departmentId: 'dept_region_east',
    name: '宁波仓储科技',
    ownerName: '张琳',
    level: '标准客户',
    city: '宁波',
    region: '华东',
    industry: '物流',
    createdAt: '2026-03-06',
    hasOpportunity: false,
    followUpStatus: '停滞观察',
    historyDeal: false,
    lifecycleStage: '预警池',
  },
  {
    id: 'customer_007',
    departmentId: 'dept_sales',
    name: '广州医联云',
    ownerName: '吴李斌',
    level: '重点客户',
    city: '广州',
    region: '华南',
    industry: '医卫',
    createdAt: '2025-11-20',
    activeSince: '2026-01-08',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: true,
    lifecycleStage: '深耕池',
  },
  {
    id: 'customer_008',
    departmentId: 'dept_sales',
    name: '佛山智造装备',
    ownerName: '盛少梅',
    level: '战略客户',
    city: '佛山',
    region: '华南',
    industry: '制造',
    createdAt: '2026-01-19',
    activeSince: '2026-02-04',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: false,
    lifecycleStage: '激活池',
  },
  {
    id: 'customer_009',
    departmentId: 'dept_region_east',
    name: '中山政务云平台',
    ownerName: '黄镇城',
    level: '重点客户',
    city: '中山',
    region: '华南',
    industry: '政府',
    createdAt: '2026-02-12',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: false,
    lifecycleStage: '激活池',
  },
  {
    id: 'customer_010',
    departmentId: 'dept_region_east',
    name: '海口文旅集团',
    ownerName: '梁俊达',
    level: '潜力客户',
    city: '海口',
    region: '海南',
    industry: '文旅',
    createdAt: '2026-03-02',
    hasOpportunity: false,
    followUpStatus: '初次联络',
    historyDeal: false,
    lifecycleStage: '新客户',
  },
  {
    id: 'customer_011',
    departmentId: 'dept_sales',
    name: '东莞半导体研究院',
    ownerName: '蔡明宇',
    level: '重点客户',
    city: '东莞',
    region: '华南',
    industry: '高技术制造',
    createdAt: '2026-01-26',
    activeSince: '2026-02-10',
    hasOpportunity: true,
    followUpStatus: '持续推进',
    historyDeal: false,
    lifecycleStage: '激活池',
  },
  {
    id: 'customer_012',
    departmentId: 'dept_sales',
    name: '珠海数智政务',
    ownerName: '黄镇城',
    level: '潜力客户',
    city: '珠海',
    region: '华南',
    industry: '政府',
    createdAt: '2026-02-23',
    hasOpportunity: false,
    followUpStatus: '初次联络',
    historyDeal: false,
    lifecycleStage: '新客户',
  },
  {
    id: 'customer_013',
    departmentId: 'dept_sales',
    name: '深圳新材实验室',
    ownerName: '蔡明宇',
    level: '标准客户',
    city: '深圳',
    region: '华南',
    industry: '高技术制造',
    createdAt: '2026-03-10',
    hasOpportunity: false,
    followUpStatus: '持续推进',
    historyDeal: false,
    lifecycleStage: '预警池',
  },
  {
    id: 'customer_014',
    departmentId: 'dept_region_east',
    name: '海南旅投平台',
    ownerName: '梁俊达',
    level: '潜力客户',
    city: '海口',
    region: '海南',
    industry: '文旅',
    createdAt: '2026-03-15',
    hasOpportunity: false,
    followUpStatus: '持续推进',
    historyDeal: false,
    lifecycleStage: '预警池',
  },
];

export const MANAGEMENT_REPORT_OPPORTUNITIES: ManagementReportOpportunityRecord[] = [
  {
    id: 'opportunity_001',
    departmentId: 'dept_region_east',
    ownerName: '张琳',
    customerName: '山东农信',
    region: '华东',
    city: '济南',
    industry: '金融',
    amount: 860000,
    stage: '谈判',
    source: '转介绍',
    agentName: '广联伙伴',
    ecosystemType: '核心伙伴',
    productSolution: 'DLP 套件',
    industrySolution: '金融数据安全',
    promised: true,
    createdAt: '2026-03-05',
    getTime: '2026-03-05',
    expectSignDate: '2026-04-10',
    revisitAt: '2026-03-25',
    stageUpdatedAt: '2026-03-20',
  },
  {
    id: 'opportunity_002',
    departmentId: 'dept_sales',
    ownerName: '李浩',
    customerName: '苏州制造',
    region: '华东',
    city: '苏州',
    industry: '制造',
    amount: 540000,
    stage: '方案',
    source: '活动',
    agentName: '苏州协同集成',
    ecosystemType: '成长伙伴',
    productSolution: '终端安全一体化',
    industrySolution: '制造研发安全',
    promised: false,
    createdAt: '2026-03-08',
    getTime: '2026-03-08',
    expectSignDate: '2026-04-25',
    revisitAt: '2026-03-28',
    stageUpdatedAt: '2026-03-18',
  },
  {
    id: 'opportunity_003',
    departmentId: 'dept_sales',
    ownerName: '王敏',
    customerName: '青岛零售集团',
    region: '华北',
    city: '青岛',
    industry: '零售',
    amount: 730000,
    stage: '初访',
    source: '官网',
    agentName: '青岛合作网络',
    ecosystemType: '沉睡伙伴',
    productSolution: '桌面管理',
    industrySolution: '零售总部终端管理',
    promised: false,
    createdAt: '2026-03-10',
    getTime: '2026-03-10',
    expectSignDate: '2026-05-05',
    revisitAt: '2026-03-12',
    stageUpdatedAt: '2026-03-10',
  },
  {
    id: 'opportunity_004',
    departmentId: 'dept_region_east',
    ownerName: '张琳',
    customerName: '杭州云计算',
    region: '华东',
    city: '杭州',
    industry: '互联网',
    amount: 420000,
    stage: '赢单',
    source: '转介绍',
    agentName: '广联伙伴',
    ecosystemType: '核心伙伴',
    productSolution: '研发数据加密',
    industrySolution: '互联网研发数据保护',
    promised: true,
    createdAt: '2026-02-18',
    getTime: '2026-02-18',
    expectSignDate: '2026-03-01',
    revisitAt: '2026-02-20',
    stageUpdatedAt: '2026-02-25',
  },
  {
    id: 'opportunity_005',
    departmentId: 'dept_sales',
    ownerName: '李浩',
    customerName: '南京制造',
    region: '华东',
    city: '南京',
    industry: '制造',
    amount: 390000,
    stage: '赢单',
    source: '渠道合作',
    agentName: '南京生态联盟',
    ecosystemType: '成长伙伴',
    productSolution: '终端准入',
    industrySolution: '制造终端准入',
    promised: true,
    createdAt: '2026-01-12',
    getTime: '2026-01-12',
    expectSignDate: '2026-02-18',
    revisitAt: '2026-02-01',
    stageUpdatedAt: '2026-01-28',
  },
  {
    id: 'opportunity_006',
    departmentId: 'dept_sales',
    ownerName: '王敏',
    customerName: '广州光中科技',
    region: '华南',
    city: '广州',
    industry: '制造',
    amount: 610000,
    stage: '30%',
    source: '搜索引擎',
    agentName: '广州制造伙伴',
    ecosystemType: '成长伙伴',
    productSolution: '终端安全一体化',
    industrySolution: '制造终端安全',
    promised: false,
    createdAt: '2026-03-18',
    getTime: '2026-03-18',
    expectSignDate: '2026-04-29',
    revisitAt: '2026-03-24',
    stageUpdatedAt: '2026-03-19',
  },
  {
    id: 'opportunity_007',
    departmentId: 'dept_region_east',
    ownerName: '张琳',
    customerName: '宁波仓储科技',
    region: '华东',
    city: '宁波',
    industry: '物流',
    amount: 280000,
    stage: '10%',
    source: '合作伙伴',
    agentName: '宁波生态集成',
    ecosystemType: '沉睡伙伴',
    productSolution: '跨网文件交换',
    industrySolution: '物流园区跨网交换',
    promised: false,
    createdAt: '2026-03-07',
    getTime: '2026-03-07',
    expectSignDate: '2026-04-05',
    revisitAt: '2026-03-08',
    stageUpdatedAt: '2026-03-07',
  },
  {
    id: 'opportunity_008',
    departmentId: 'dept_sales',
    ownerName: '李浩',
    customerName: '山东农信',
    region: '华北',
    city: '济南',
    industry: '金融',
    amount: 920000,
    stage: '50%',
    source: '公开课',
    agentName: '广联伙伴',
    ecosystemType: '核心伙伴',
    productSolution: '零信任访问',
    industrySolution: '金融总部零信任',
    promised: true,
    createdAt: '2026-02-26',
    getTime: '2026-02-26',
    expectSignDate: '2026-03-30',
    revisitAt: '2026-03-01',
    stageUpdatedAt: '2026-03-02',
  },
  {
    id: 'opportunity_009',
    departmentId: 'dept_sales',
    ownerName: '吴李斌',
    customerName: '广州医联云',
    region: '华南',
    city: '广州',
    industry: '医卫',
    amount: 760000,
    stage: '30%',
    source: '合作伙伴',
    agentName: '广州医疗伙伴',
    ecosystemType: '核心伙伴',
    productSolution: '终端准入',
    industrySolution: '医院终端安全',
    promised: true,
    createdAt: '2026-03-11',
    getTime: '2026-03-11',
    expectSignDate: '2026-04-18',
    revisitAt: '2026-03-25',
    stageUpdatedAt: '2026-03-21',
  },
  {
    id: 'opportunity_010',
    departmentId: 'dept_sales',
    ownerName: '盛少梅',
    customerName: '佛山智造装备',
    region: '华南',
    city: '佛山',
    industry: '制造',
    amount: 680000,
    stage: '50%',
    source: '渠道合作',
    agentName: '佛山智造伙伴',
    ecosystemType: '成长伙伴',
    productSolution: 'DLP 套件',
    industrySolution: '制造研发安全',
    promised: true,
    createdAt: '2026-02-14',
    getTime: '2026-02-14',
    expectSignDate: '2026-03-22',
    revisitAt: '2026-03-01',
    stageUpdatedAt: '2026-03-05',
  },
  {
    id: 'opportunity_011',
    departmentId: 'dept_region_east',
    ownerName: '黄镇城',
    customerName: '中山政务云平台',
    region: '华南',
    city: '中山',
    industry: '政府',
    amount: 840000,
    stage: '方案',
    source: '搜索引擎',
    agentName: '政务云生态伙伴',
    ecosystemType: '核心伙伴',
    productSolution: '跨网文件交换',
    industrySolution: '政务跨网交换',
    promised: false,
    createdAt: '2026-03-03',
    getTime: '2026-03-03',
    expectSignDate: '2026-04-12',
    revisitAt: '2026-03-12',
    stageUpdatedAt: '2026-03-10',
  },
  {
    id: 'opportunity_012',
    departmentId: 'dept_region_east',
    ownerName: '梁俊达',
    customerName: '海口文旅集团',
    region: '海南',
    city: '海口',
    industry: '文旅',
    amount: 470000,
    stage: '10%',
    source: '活动',
    agentName: '海南生态联盟',
    ecosystemType: '成长伙伴',
    productSolution: '移动办公安全',
    industrySolution: '文旅移动办公',
    promised: false,
    createdAt: '2026-03-17',
    getTime: '2026-03-17',
    expectSignDate: '2026-05-09',
    revisitAt: '2026-03-18',
    stageUpdatedAt: '2026-03-17',
  },
  {
    id: 'opportunity_013',
    departmentId: 'dept_sales',
    ownerName: '蔡明宇',
    customerName: '东莞半导体研究院',
    region: '华南',
    city: '东莞',
    industry: '高技术制造',
    amount: 980000,
    stage: '谈判',
    source: '转介绍',
    agentName: '高端制造伙伴',
    ecosystemType: '核心伙伴',
    productSolution: '研发数据加密',
    industrySolution: '芯片研发数据保护',
    promised: true,
    createdAt: '2026-02-22',
    getTime: '2026-02-22',
    expectSignDate: '2026-03-28',
    revisitAt: '2026-03-06',
    stageUpdatedAt: '2026-03-08',
  },
  {
    id: 'opportunity_014',
    departmentId: 'dept_sales',
    ownerName: '盛少梅',
    customerName: '青岛零售集团',
    region: '华北',
    city: '青岛',
    industry: '零售',
    amount: 320000,
    stage: '10%',
    source: '官网',
    agentName: '青岛合作网络',
    ecosystemType: '沉睡伙伴',
    productSolution: '桌面管理',
    industrySolution: '零售终端管理',
    promised: false,
    createdAt: '2026-01-25',
    getTime: '2026-01-25',
    expectSignDate: '2026-04-15',
    revisitAt: '2026-01-28',
    stageUpdatedAt: '2026-01-29',
  },
];

export const MANAGEMENT_REPORT_CONTRACTS: ManagementReportContractRecord[] = [
  {
    id: 'contract_001',
    departmentId: 'dept_region_east',
    customerName: '山东农信',
    ownerName: '张琳',
    amount: 510000,
    createdAt: '2026-03-15',
    signDate: '2026-03-19',
    expectedAcceptanceDate: '2026-04-20',
  },
  {
    id: 'contract_002',
    departmentId: 'dept_sales',
    customerName: '苏州制造',
    ownerName: '李浩',
    amount: 360000,
    createdAt: '2026-03-14',
    signDate: '2026-03-16',
    acceptedAt: '2026-03-30',
    expectedAcceptanceDate: '2026-03-28',
  },
  {
    id: 'contract_003',
    departmentId: 'dept_region_east',
    customerName: '杭州云计算',
    ownerName: '张琳',
    amount: 280000,
    createdAt: '2026-02-08',
    signDate: '2026-02-12',
    expectedAcceptanceDate: '2026-03-20',
  },
  {
    id: 'contract_004',
    departmentId: 'dept_sales',
    customerName: '青岛零售集团',
    ownerName: '王敏',
    amount: 190000,
    createdAt: '2026-01-18',
    signDate: '2026-01-21',
    expectedAcceptanceDate: '2026-02-28',
  },
  {
    id: 'contract_005',
    departmentId: 'dept_sales',
    customerName: '广州医联云',
    ownerName: '吴李斌',
    amount: 430000,
    createdAt: '2026-02-14',
    signDate: '2026-02-18',
    expectedAcceptanceDate: '2026-03-30',
  },
  {
    id: 'contract_006',
    departmentId: 'dept_sales',
    customerName: '佛山智造装备',
    ownerName: '盛少梅',
    amount: 520000,
    createdAt: '2026-03-06',
    signDate: '2026-03-10',
    acceptedAt: '2026-03-29',
    expectedAcceptanceDate: '2026-03-25',
  },
  {
    id: 'contract_007',
    departmentId: 'dept_region_east',
    customerName: '中山政务云平台',
    ownerName: '黄镇城',
    amount: 610000,
    createdAt: '2026-02-24',
    signDate: '2026-02-26',
    expectedAcceptanceDate: '2026-04-08',
  },
  {
    id: 'contract_008',
    departmentId: 'dept_sales',
    customerName: '东莞半导体研究院',
    ownerName: '蔡明宇',
    amount: 880000,
    createdAt: '2026-03-02',
    signDate: '2026-03-08',
    expectedAcceptanceDate: '2026-04-12',
  },
];

export const MANAGEMENT_REPORT_PAYMENT_PLANS: ManagementReportPaymentPlanRecord[] = [
  {
    id: 'plan_001',
    contractId: 'contract_001',
    amount: 180000,
    receiveDate: '2026-03-25',
    status: 'PLANNED',
  },
  {
    id: 'plan_002',
    contractId: 'contract_002',
    amount: 240000,
    receiveDate: '2026-03-28',
    status: 'RECEIVED',
  },
  {
    id: 'plan_003',
    contractId: 'contract_003',
    amount: 160000,
    receiveDate: '2026-03-18',
    status: 'OVERDUE',
  },
  {
    id: 'plan_004',
    contractId: 'contract_004',
    amount: 90000,
    receiveDate: '2026-02-25',
    status: 'OVERDUE',
  },
  {
    id: 'plan_005',
    contractId: 'contract_003',
    amount: 120000,
    receiveDate: '2026-04-25',
    status: 'PLANNED',
  },
  {
    id: 'plan_006',
    contractId: 'contract_005',
    amount: 220000,
    receiveDate: '2026-03-20',
    status: 'OVERDUE',
  },
  {
    id: 'plan_007',
    contractId: 'contract_006',
    amount: 300000,
    receiveDate: '2026-03-27',
    status: 'RECEIVED',
  },
  {
    id: 'plan_008',
    contractId: 'contract_007',
    amount: 260000,
    receiveDate: '2026-03-24',
    status: 'PLANNED',
  },
  {
    id: 'plan_009',
    contractId: 'contract_008',
    amount: 380000,
    receiveDate: '2026-03-14',
    status: 'OVERDUE',
  },
];

export const MANAGEMENT_REPORT_PAYMENTS: ManagementReportPaymentRecord[] = [
  {
    id: 'payment_001',
    contractId: 'contract_002',
    amount: 240000,
    receiveDate: '2026-03-29',
  },
  {
    id: 'payment_002',
    contractId: 'contract_004',
    amount: 50000,
    receiveDate: '2026-02-26',
  },
  {
    id: 'payment_003',
    contractId: 'contract_003',
    amount: 70000,
    receiveDate: '2026-02-20',
  },
  {
    id: 'payment_004',
    contractId: 'contract_001',
    amount: 140000,
    receiveDate: '2026-03-27',
  },
  {
    id: 'payment_005',
    contractId: 'contract_005',
    amount: 120000,
    receiveDate: '2026-03-12',
  },
  {
    id: 'payment_006',
    contractId: 'contract_006',
    amount: 300000,
    receiveDate: '2026-03-28',
  },
  {
    id: 'payment_007',
    contractId: 'contract_008',
    amount: 190000,
    receiveDate: '2026-03-15',
  },
];
