import type { ContractReviewRuleSetRecord } from '../../shared/types/domain';

export const CONTRACT_REVIEW_RULE_SET: ContractReviewRuleSetRecord = {
  id: 'rule_set_company_contract_v1',
  code: 'company-commercial-v1',
  version: '2026.04',
  title: '公司商务合同审核基线',
  summary: '基于公司销售风控检视表整理的首版商务合同审核规则快照。',
  issuedAt: '2026-04-05T00:00:00.000Z',
  itemCount: 6,
  items: [
    {
      code: 'CR-IP-001',
      category: '知识产权',
      title: '知识产权或源代码归客户独有',
      description: '知识产权、源代码或通用需求成果归客户独有，违反公司一票否决要求。',
      riskLevel: 'HIGH',
      isVeto: true,
      sourceClause: '一票否决项#1 / 2.7 知识产权',
      keywords: ['知识产权', '源代码', '客户独有'],
      suggestion: '改为乙方享有知识产权，甲方仅在合同约定范围内享有使用权。',
    },
    {
      code: 'CR-PAY-001',
      category: '付款条件',
      title: '付款条款缺少验收前置条件',
      description: '付款节点未与验收或交付条件绑定，存在先付款后争议风险。',
      riskLevel: 'HIGH',
      isVeto: false,
      sourceClause: '1.3 付款条件',
      keywords: ['付款', '发票', '验收'],
      suggestion: '补充以验收通过为付款前提，并明确首付款、到货款、验收款对应条件。',
    },
    {
      code: 'CR-LIA-001',
      category: '违约责任',
      title: '违约责任上限缺失或显著过高',
      description: '违约责任未设置上限，或超过公司允许区间，容易引发赔付失衡。',
      riskLevel: 'HIGH',
      isVeto: false,
      sourceClause: '1.4 违约罚则 / 一票否决项#4',
      keywords: ['违约', '赔偿', '责任上限'],
      suggestion: '补充违约责任上限，并限制在合同总金额的合理比例区间内。',
    },
    {
      code: 'CR-DATA-001',
      category: '数据使用',
      title: '数据使用范围表述过宽',
      description: '对客户数据或业务资料的使用范围、用途和保存期限约束不足。',
      riskLevel: 'MEDIUM',
      isVeto: false,
      sourceClause: '风险评级标准 / 建议补充保护性条款',
      keywords: ['数据', '使用', '共享'],
      suggestion: '限定数据用途、处理范围、访问角色和保存期限，避免泛化授权。',
    },
    {
      code: 'CR-INV-001',
      category: '开票',
      title: '开票名称缺少“*软件*”前缀',
      description: '软件产品开票名称不符合公司开票规范，属于高风险问题。',
      riskLevel: 'HIGH',
      isVeto: true,
      sourceClause: '2.11 开票 / 一票否决项#3',
      keywords: ['开票', '软件', '发票'],
      suggestion: '按标准模板补充“*软件*”前缀，并分离软件、硬件、技术服务开票名称。',
    },
    {
      code: 'CR-DISCOUNT-001',
      category: '折扣率',
      title: '折扣低于审批红线',
      description: '报价折扣低于公司权限红线且未体现特价审批依据。',
      riskLevel: 'HIGH',
      isVeto: true,
      sourceClause: '2.3 折扣率 / 一票否决项#5',
      keywords: ['折扣', '特价审批', '报价'],
      suggestion: '补充特价审批依据，或将折扣调整回权限允许区间。',
    },
  ],
};
