import {
  Aim,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Back,
  ChatLineRound,
  CircleCheckFilled,
  CircleCloseFilled,
  CirclePlusFilled,
  Close,
  Collection,
  CollectionTag,
  Connection,
  CopyDocument,
  Cpu,
  DataAnalysis,
  DataBoard,
  DataLine,
  Delete,
  Document,
  DocumentChecked,
  Download,
  EditPen,
  Expand,
  Files,
  Filter,
  Flag,
  Fold,
  Folder,
  FolderOpened,
  Grid,
  Histogram,
  Key,
  Link,
  List,
  Loading,
  Lock,
  MagicStick,
  Memo,
  Menu,
  Monitor,
  Money,
  OfficeBuilding,
  Operation,
  PieChart,
  Rank,
  Reading,
  Refresh,
  Search,
  Setting,
  SuccessFilled,
  Tickets,
  Timer,
  TrendCharts,
  UploadFilled,
  User,
  View,
  WarningFilled,
  WarnTriangleFilled,
} from '@element-plus/icons-vue';

export const UiIcons = {
  analysis: DataAnalysis,
  audit: View,
  back: Back,
  chart: TrendCharts,
  close: Close,
  collapse: Fold,
  company: OfficeBuilding,
  copy: CopyDocument,
  contract: DocumentChecked,
  customer: OfficeBuilding,
  dashboard: DataBoard,
  dataLine: DataLine,
  delete: Delete,
  detail: List,
  download: Download,
  edit: EditPen,
  error: CircleCloseFilled,
  expand: Expand,
  files: Files,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  folderOpened: FolderOpened,
  governance: Setting,
  grid: Grid,
  histogram: Histogram,
  info: Aim,
  link: Link,
  loading: Loading,
  login: Key,
  magic: MagicStick,
  memo: Memo,
  menu: Menu,
  monitor: Monitor,
  money: Money,
  object: Collection,
  password: Lock,
  pie: PieChart,
  plus: CirclePlusFilled,
  query: ChatLineRound,
  ranking: Rank,
  reading: Reading,
  refresh: Refresh,
  result: Document,
  risk: WarnTriangleFilled,
  search: Search,
  success: CircleCheckFilled,
  successAlt: SuccessFilled,
  template: Tickets,
  templateLibrary: CollectionTag,
  time: Timer,
  upload: UploadFilled,
  user: User,
  warning: WarningFilled,
  workflow: Operation,
  connection: Connection,
  management: Cpu,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
} as const;

export const UiIconGroups = {
  navigation: {
    analysis: DataAnalysis,
    management: Cpu,
    contract: DocumentChecked,
    permission: User,
    template: Tickets,
    connection: Connection,
    aiProfile: MagicStick,
    audit: View,
  },
  action: {
    search: Search,
    filter: Filter,
    refresh: Refresh,
    upload: UploadFilled,
    download: Download,
    export: Download,
    back: Back,
    close: Close,
    expand: Expand,
    collapse: Fold,
    edit: EditPen,
    delete: Delete,
    detail: Document,
  },
  status: {
    success: CircleCheckFilled,
    warning: WarningFilled,
    danger: CircleCloseFilled,
    blocked: WarnTriangleFilled,
    running: Loading,
    info: Aim,
    offline: CircleCloseFilled,
  },
  object: {
    customer: OfficeBuilding,
    owner: User,
    contract: DocumentChecked,
    template: Tickets,
    policy: Setting,
    connection: Connection,
    auditEvent: View,
    dataTable: Grid,
    chart: TrendCharts,
    wecom: ChatLineRound,
    report: DataBoard,
    profile: MagicStick,
  },
  risk: {
    critical: WarnTriangleFilled,
    high: WarnTriangleFilled,
    medium: WarningFilled,
    low: CircleCheckFilled,
    neutral: Aim,
  },
} as const;

export type UiIconName = keyof typeof UiIcons;
export type UiIconComponent = (typeof UiIcons)[keyof typeof UiIcons];
