export interface SemanticFieldSeed {
  tableName: string;
  fieldName: string;
  fieldLabel: string;
  businessMeaning: string;
  dataType: string;
  resource?: string;
  sensitiveLevel?: string;
  dictionaryKey?: string;
}

export interface SemanticMetricSeed {
  metricKey: string;
  metricLabel: string;
  metricFormula: string;
  defaultTable: string;
  businessMeaning: string;
}

/**
 * 生成分析库 P0 语义字段目录种子。
 *
 * 参数说明：无。
 * 返回值说明：返回可幂等写入 `semantic_field_catalog` 的字段清单。
 * 调用注意事项：这里只登记 DWD/Facts/语义目录字段，不登记 ODS 原始 JSON，避免 Text-to-SQL 绕过脱敏和权限边界。
 */
export function buildAnalysisWarehouseSemanticFieldSeeds(): SemanticFieldSeed[] {
  return [
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'user_id',
      fieldLabel: 'CRM 用户 ID',
      businessMeaning: 'CRM 用户唯一标识，用于负责人、创建人、指派员工和企微身份映射。',
      dataType: 'string',
      resource: 'users',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'username',
      fieldLabel: '登录账号',
      businessMeaning: 'CRM 登录账号，可用于联调账号识别和权限视角核对。',
      dataType: 'string',
      resource: 'users',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'user_name',
      fieldLabel: '姓名',
      businessMeaning: 'CRM 用户姓名，用于负责人排行和权限验证报告展示。',
      dataType: 'string',
      resource: 'users',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'role_code',
      fieldLabel: '角色编码',
      businessMeaning: '联软 CRM 角色编码，用于区分超管、区管、渠道管理员和员工视角。',
      dataType: 'string',
      resource: 'users',
      dictionaryKey: 'roles',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'role_name',
      fieldLabel: '角色名称',
      businessMeaning: '联软 CRM 角色中文名称，用于报告中说明当前数据口径来自哪个角色视角。',
      dataType: 'string',
      resource: 'users',
      dictionaryKey: 'roles',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'wecom_userid',
      fieldLabel: '企业微信 userid',
      businessMeaning: '企业微信成员与 CRM 用户的映射键，只用于身份匹配，不默认进入业务报告正文。',
      dataType: 'string',
      resource: 'users',
      sensitiveLevel: 'INTERNAL',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'department_name',
      fieldLabel: '部门名称',
      businessMeaning: 'CRM 用户所属部门名称，用于按组织或团队统计经营表现。',
      dataType: 'string',
      resource: 'users',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'region',
      fieldLabel: '区域',
      businessMeaning: '用户所属区域，用于区域权限裁剪和区域经营分析。',
      dataType: 'string',
      resource: 'users',
      dictionaryKey: 'regions',
    },
    {
      tableName: 'dim_lianruan_user',
      fieldName: 'big_region',
      fieldLabel: '大区',
      businessMeaning: '用户所属大区，用于大区口径权限裁剪和经营分析。',
      dataType: 'string',
      resource: 'users',
      dictionaryKey: 'bigRegions',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'partner_id',
      fieldLabel: '服务商 ID',
      businessMeaning: '合作伙伴、服务商、渠道商、代理商的统一主键。',
      dataType: 'string',
      resource: 'partners',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'partner_name',
      fieldLabel: '服务商名称',
      businessMeaning: '合作伙伴、服务商、渠道商、代理商的统一展示名称。',
      dataType: 'string',
      resource: 'partners',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'short_name',
      fieldLabel: '服务商简称',
      businessMeaning: '服务商简称，用于表格和企微报告中的紧凑展示。',
      dataType: 'string',
      resource: 'partners',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'partner_level',
      fieldLabel: '合作级别编码',
      businessMeaning: '服务商合作级别编码，用于分组统计和字典翻译。',
      dataType: 'string',
      resource: 'partners',
      dictionaryKey: 'partnerLevels',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'partner_level_name',
      fieldLabel: '合作级别',
      businessMeaning: '服务商合作级别中文名称，用于服务商画像分布。',
      dataType: 'string',
      resource: 'partners',
      dictionaryKey: 'partnerLevels',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'is_technical_service_provider',
      fieldLabel: '是否技术服务商',
      businessMeaning: '标识服务商是否具备技术服务商属性。',
      dataType: 'boolean',
      resource: 'partners',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'technical_service_provider_type',
      fieldLabel: '技术服务商类型',
      businessMeaning: '技术服务商细分类型，用于服务能力画像。',
      dataType: 'string',
      resource: 'partners',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'parent_partner_id',
      fieldLabel: '上级服务商 ID',
      businessMeaning: '渠道父子层级关系字段，用于渠道管理员权限和下级渠道汇总。',
      dataType: 'string',
      resource: 'partners',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'region',
      fieldLabel: '区域',
      businessMeaning: '服务商所属区域，用于区域服务商数量、商机和订单分析。',
      dataType: 'string',
      resource: 'partners',
      dictionaryKey: 'regions',
    },
    {
      tableName: 'dim_lianruan_partner',
      fieldName: 'created_at',
      fieldLabel: '加入时间',
      businessMeaning: '服务商加入或创建时间，用于统计最近一年新增服务商。',
      dataType: 'datetime',
      resource: 'partners',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'customer_id',
      fieldLabel: '客户 ID',
      businessMeaning: '客户视图稳定主键，用于关联报备、商机、报价和订单。',
      dataType: 'string',
      resource: 'customers',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'customer_name',
      fieldLabel: '客户名称',
      businessMeaning: '客户主数据名称。',
      dataType: 'string',
      resource: 'customers',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'status_name',
      fieldLabel: '客户生命周期状态',
      businessMeaning: '客户当前生命周期中文状态，用于客户阶段分布。',
      dataType: 'string',
      resource: 'customers',
      dictionaryKey: 'customerStatuses',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'registration_count',
      fieldLabel: '报备数量',
      businessMeaning: '客户关联的报备数量，用于识别未报备客户。',
      dataType: 'number',
      resource: 'customers',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'opportunity_count',
      fieldLabel: '商机数量',
      businessMeaning: '客户关联的商机数量，用于识别未建商机客户。',
      dataType: 'number',
      resource: 'customers',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'quote_count',
      fieldLabel: '报价数量',
      businessMeaning: '客户关联的报价数量，用于识别有商机未报价客户。',
      dataType: 'number',
      resource: 'customers',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'order_count',
      fieldLabel: '订单数量',
      businessMeaning: '客户关联的订单数量，用于识别未下单客户。',
      dataType: 'number',
      resource: 'customers',
    },
    {
      tableName: 'dim_lianruan_customer',
      fieldName: 'latest_activity_at',
      fieldLabel: '最近活动时间',
      businessMeaning: '客户最近业务活动时间，用于沉睡客户识别。',
      dataType: 'datetime',
      resource: 'customers',
    },
    {
      tableName: 'fact_lianruan_registration',
      fieldName: 'registration_id',
      fieldLabel: '报备 ID',
      businessMeaning: '报备唯一标识，用于报备明细和漏斗分析。',
      dataType: 'string',
      resource: 'registrations',
    },
    {
      tableName: 'fact_lianruan_registration',
      fieldName: 'customer_name',
      fieldLabel: '报备客户名称',
      businessMeaning: '报备记录中的客户名称。',
      dataType: 'string',
      resource: 'registrations',
    },
    {
      tableName: 'fact_lianruan_registration',
      fieldName: 'status',
      fieldLabel: '报备状态',
      businessMeaning: '报备当前状态，用于有效报备统计。',
      dataType: 'string',
      resource: 'registrations',
      dictionaryKey: 'registrationStatuses',
    },
    {
      tableName: 'fact_lianruan_registration',
      fieldName: 'partner_id',
      fieldLabel: '报备服务商 ID',
      businessMeaning: '报备关联的服务商或渠道 ID，用于渠道报备数量和报备转化分析。',
      dataType: 'string',
      resource: 'registrations',
    },
    {
      tableName: 'fact_lianruan_registration',
      fieldName: 'region',
      fieldLabel: '报备区域',
      businessMeaning: '报备标准化区域，用于区域报备数和区域漏斗分析。',
      dataType: 'string',
      resource: 'registrations',
      dictionaryKey: 'regions',
    },
    {
      tableName: 'fact_lianruan_registration',
      fieldName: 'big_region',
      fieldLabel: '报备大区',
      businessMeaning: '报备标准化大区，用于大区报备数和大区漏斗分析。',
      dataType: 'string',
      resource: 'registrations',
      dictionaryKey: 'bigRegions',
    },
    {
      tableName: 'fact_lianruan_registration',
      fieldName: 'created_at',
      fieldLabel: '报备创建时间',
      businessMeaning: '报备创建时间，用于时间范围筛选和报备趋势分析。',
      dataType: 'datetime',
      resource: 'registrations',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'opportunity_id',
      fieldLabel: '商机 ID',
      businessMeaning: '商机唯一标识，用于商机明细、报价和订单关联。',
      dataType: 'string',
      resource: 'opportunities',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'opportunity_name',
      fieldLabel: '商机名称',
      businessMeaning: '商机项目名称，用于风险清单和明细展示。',
      dataType: 'string',
      resource: 'opportunities',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'stage_name',
      fieldLabel: '商机阶段',
      businessMeaning: '商机阶段中文名称，用于阶段分布和风险判断。',
      dataType: 'string',
      resource: 'opportunities',
      dictionaryKey: 'opportunityStages',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'amount',
      fieldLabel: '商机金额',
      businessMeaning: 'MVP 阶段使用 opportunities.amount 作为商机金额。',
      dataType: 'decimal',
      resource: 'opportunities',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'owner_name',
      fieldLabel: '商机负责人',
      businessMeaning: '商机负责人姓名，用于负责人商机金额排行。',
      dataType: 'string',
      resource: 'opportunities',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'partner_name',
      fieldLabel: '服务商名称',
      businessMeaning: '商机关联服务商名称，用于服务商商机数量和金额统计。',
      dataType: 'string',
      resource: 'opportunities',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'region',
      fieldLabel: '区域',
      businessMeaning: '商机所属区域，用于山东区域、本月各区域等问数。',
      dataType: 'string',
      resource: 'opportunities',
      dictionaryKey: 'regions',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'expected_close_at',
      fieldLabel: '预计成交时间',
      businessMeaning: '商机预计成交时间，用于预测和跟进风险辅助判断。',
      dataType: 'datetime',
      resource: 'opportunities',
    },
    {
      tableName: 'fact_lianruan_opportunity',
      fieldName: 'source_updated_at',
      fieldLabel: '商机更新时间',
      businessMeaning: '用于识别超过两周未更新商机，后续有 lastFollowUpAt 时优先使用最后跟进时间。',
      dataType: 'datetime',
      resource: 'opportunities',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'quote_id',
      fieldLabel: '报价 ID',
      businessMeaning: '报价唯一标识，用于报价明细和漏斗分析。',
      dataType: 'string',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'customer_id',
      fieldLabel: '报价客户 ID',
      businessMeaning: '报价关联客户 ID，用于客户到报价和报价转订单分析。',
      dataType: 'string',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'customer_name',
      fieldLabel: '报价客户名称',
      businessMeaning: '报价关联客户名称，用于报价明细展示。',
      dataType: 'string',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'opportunity_id',
      fieldLabel: '关联商机 ID',
      businessMeaning: '报价关联商机 ID，用于商机转报价漏斗分析。',
      dataType: 'string',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'partner_id',
      fieldLabel: '报价服务商 ID',
      businessMeaning: '报价关联服务商 ID，用于服务商报价数量和金额分析。',
      dataType: 'string',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'assigned_partner_id',
      fieldLabel: '报价归属服务商 ID',
      businessMeaning: '报价归属服务商 ID，用于渠道账号和下级渠道权限裁剪。',
      dataType: 'string',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'parent_partner_id',
      fieldLabel: '报价上级服务商 ID',
      businessMeaning: '报价上级服务商 ID，用于渠道链路权限和上级渠道汇总。',
      dataType: 'string',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'amount',
      fieldLabel: '报价金额',
      businessMeaning: 'MVP 阶段优先使用 quotes.amount，缺失时由转换层回退报价总额。',
      dataType: 'decimal',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'status',
      fieldLabel: '报价状态',
      businessMeaning: '报价当前状态，用于报价阶段和漏斗分析。',
      dataType: 'string',
      resource: 'quotes',
      dictionaryKey: 'quoteStatuses',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'region',
      fieldLabel: '报价区域',
      businessMeaning: '报价标准化区域；联软按对象自身、商机、渠道和负责人顺序继承补齐，用于区域报价分析。',
      dataType: 'string',
      resource: 'quotes',
      dictionaryKey: 'regions',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'big_region',
      fieldLabel: '报价大区',
      businessMeaning: '报价标准化大区；联软按继承规则补齐，用于大区报价分析。',
      dataType: 'string',
      resource: 'quotes',
      dictionaryKey: 'bigRegions',
    },
    {
      tableName: 'fact_lianruan_quote',
      fieldName: 'created_at',
      fieldLabel: '报价创建时间',
      businessMeaning: '报价创建时间，用于报价趋势、商机转报价和报价未下单分析。',
      dataType: 'datetime',
      resource: 'quotes',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'order_id',
      fieldLabel: '订单 ID',
      businessMeaning: '订单唯一标识，用于订单明细和下单统计。',
      dataType: 'string',
      resource: 'orders',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'customer_id',
      fieldLabel: '订单客户 ID',
      businessMeaning: '订单关联客户 ID，用于客户下单、复购和漏斗分析。',
      dataType: 'string',
      resource: 'orders',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'customer_name',
      fieldLabel: '订单客户名称',
      businessMeaning: '订单关联客户名称，用于订单明细展示。',
      dataType: 'string',
      resource: 'orders',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'amount',
      fieldLabel: '订单金额',
      businessMeaning: 'MVP 阶段优先使用 orders.amount，缺失时由转换层回退其它总额字段。',
      dataType: 'decimal',
      resource: 'orders',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'status',
      fieldLabel: '订单状态',
      businessMeaning: '订单状态；有效订单默认排除已取消、已作废、已驳回和已删除。',
      dataType: 'string',
      resource: 'orders',
      dictionaryKey: 'orderStatuses',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'region',
      fieldLabel: '订单区域',
      businessMeaning: '订单标准化区域；联软按对象自身、报价、商机、渠道和负责人顺序继承补齐，用于区域订单分析。',
      dataType: 'string',
      resource: 'orders',
      dictionaryKey: 'regions',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'big_region',
      fieldLabel: '订单大区',
      businessMeaning: '订单标准化大区；联软按继承规则补齐，用于大区订单分析。',
      dataType: 'string',
      resource: 'orders',
      dictionaryKey: 'bigRegions',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'deal_at',
      fieldLabel: '下单时间',
      businessMeaning: '订单成交或下单时间，用于本季度订单趋势和下单口径统计。',
      dataType: 'datetime',
      resource: 'orders',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'assigned_partner_id',
      fieldLabel: '订单归属服务商 ID',
      businessMeaning: '订单归属服务商 ID，用于渠道账号和下级渠道权限裁剪。',
      dataType: 'string',
      resource: 'orders',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'parent_partner_id',
      fieldLabel: '订单上级服务商 ID',
      businessMeaning: '订单上级服务商 ID，用于渠道链路权限和上级渠道汇总。',
      dataType: 'string',
      resource: 'orders',
    },
    {
      tableName: 'fact_lianruan_order',
      fieldName: 'partner_id',
      fieldLabel: '服务商 ID',
      businessMeaning: '订单关联服务商 ID，用于服务商订单数量和金额统计。',
      dataType: 'string',
      resource: 'orders',
    },
  ];
}

/**
 * 生成分析库 P0 语义指标目录种子。
 *
 * 参数说明：无。
 * 返回值说明：返回可幂等写入 `semantic_metric_catalog` 的指标清单。
 * 调用注意事项：指标公式只描述业务口径，真正执行前仍需经过受控 SQL 校验和权限注入。
 */
export function buildAnalysisWarehouseSemanticMetricSeeds(): SemanticMetricSeed[] {
  return [
    {
      metricKey: 'partner_count',
      metricLabel: '服务商数量',
      metricFormula: 'COUNT(DISTINCT dim_lianruan_partner.partner_id)',
      defaultTable: 'dim_lianruan_partner',
      businessMeaning: '统计当前权限和筛选范围内的服务商数量。',
    },
    {
      metricKey: 'customer_count',
      metricLabel: '客户数量',
      metricFormula: 'COUNT(DISTINCT dim_lianruan_customer.customer_id)',
      defaultTable: 'dim_lianruan_customer',
      businessMeaning: '统计当前权限和筛选范围内的客户数量。',
    },
    {
      metricKey: 'registration_count',
      metricLabel: '报备数量',
      metricFormula: 'COUNT(DISTINCT fact_lianruan_registration.registration_id)',
      defaultTable: 'fact_lianruan_registration',
      businessMeaning: '统计当前权限和筛选范围内的报备数量。',
    },
    {
      metricKey: 'opportunity_count',
      metricLabel: '商机数量',
      metricFormula: 'COUNT(DISTINCT fact_lianruan_opportunity.opportunity_id)',
      defaultTable: 'fact_lianruan_opportunity',
      businessMeaning: '统计当前权限和筛选范围内的商机数量。',
    },
    {
      metricKey: 'opportunity_amount',
      metricLabel: '商机金额',
      metricFormula: 'SUM(fact_lianruan_opportunity.amount)',
      defaultTable: 'fact_lianruan_opportunity',
      businessMeaning: '统计当前权限和筛选范围内的商机金额。',
    },
    {
      metricKey: 'quote_count',
      metricLabel: '报价数量',
      metricFormula: 'COUNT(DISTINCT fact_lianruan_quote.quote_id)',
      defaultTable: 'fact_lianruan_quote',
      businessMeaning: '统计当前权限和筛选范围内的报价数量。',
    },
    {
      metricKey: 'quote_amount',
      metricLabel: '报价金额',
      metricFormula: 'SUM(fact_lianruan_quote.amount)',
      defaultTable: 'fact_lianruan_quote',
      businessMeaning: '统计当前权限和筛选范围内的报价金额。',
    },
    {
      metricKey: 'order_count',
      metricLabel: '订单数量',
      metricFormula: 'COUNT(DISTINCT fact_lianruan_order.order_id)',
      defaultTable: 'fact_lianruan_order',
      businessMeaning: '统计当前权限和筛选范围内的订单数量。',
    },
    {
      metricKey: 'order_amount',
      metricLabel: '订单金额',
      metricFormula: 'SUM(fact_lianruan_order.amount)',
      defaultTable: 'fact_lianruan_order',
      businessMeaning: '统计当前权限和筛选范围内的订单金额。',
    },
    {
      metricKey: 'effective_order_count',
      metricLabel: '有效订单数量',
      metricFormula: "COUNT(DISTINCT CASE WHEN fact_lianruan_order.status NOT IN ('cancelled','canceled','void','rejected','deleted') THEN fact_lianruan_order.order_id END)",
      defaultTable: 'fact_lianruan_order',
      businessMeaning: '统计有效订单数量，默认排除已取消、已作废、已驳回和已删除订单。',
    },
    {
      metricKey: 'effective_order_amount',
      metricLabel: '有效订单金额',
      metricFormula: "SUM(CASE WHEN fact_lianruan_order.status NOT IN ('cancelled','canceled','void','rejected','deleted') THEN fact_lianruan_order.amount ELSE 0 END)",
      defaultTable: 'fact_lianruan_order',
      businessMeaning: '统计有效订单金额，默认排除已取消、已作废、已驳回和已删除订单。',
    },
    {
      metricKey: 'stale_opportunity_count',
      metricLabel: '超过两周未更新商机数量',
      metricFormula: "COUNT(DISTINCT CASE WHEN DATEDIFF(CURDATE(), fact_lianruan_opportunity.source_updated_at) > 14 AND COALESCE(fact_lianruan_opportunity.stage, fact_lianruan_opportunity.status, '') NOT IN ('won','lost','已成交','已失单') THEN fact_lianruan_opportunity.opportunity_id END)",
      defaultTable: 'fact_lianruan_opportunity',
      businessMeaning: '统计超过 14 个自然日未更新且未成交、未失单的商机数量，P3 阶段使用商机更新时间判断。',
    },
    {
      metricKey: 'inactive_customer_count',
      metricLabel: '最近 30 天未活跃客户数量',
      metricFormula: 'COUNT(DISTINCT CASE WHEN dim_lianruan_customer.latest_activity_at IS NULL OR DATEDIFF(CURDATE(), dim_lianruan_customer.latest_activity_at) > 30 THEN dim_lianruan_customer.customer_id END)',
      defaultTable: 'dim_lianruan_customer',
      businessMeaning: '统计最近 30 天未活跃客户数量，优先使用客户视图 latest_activity_at 判断。',
    },
    {
      metricKey: 'registration_to_order_funnel',
      metricLabel: '报备到订单转化漏斗',
      metricFormula: 'COUNT(DISTINCT registration_id) / COUNT(DISTINCT opportunity_id) / COUNT(DISTINCT quote_id) / COUNT(DISTINCT order_id)',
      defaultTable: 'fact_lianruan_registration',
      businessMeaning: '描述报备数、商机数、报价数、订单数及各阶段转化率；实际执行由受控模板或 SQL Guard 后的查询生成。',
    },
  ];
}
