CREATE TABLE IF NOT EXISTS ods_lianruan_sync_runs (
  id VARCHAR(96) NOT NULL PRIMARY KEY,
  source_type VARCHAR(32) NOT NULL,
  sync_mode VARCHAR(32) NOT NULL,
  dry_run TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  requested_by VARCHAR(128) NOT NULL,
  requested_by_name VARCHAR(255) NULL,
  resources_json LONGTEXT NOT NULL,
  resource_results_json LONGTEXT NOT NULL,
  config_snapshot_json LONGTEXT NOT NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NULL,
  duration_ms INT NULL,
  failure_reason TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX idx_ods_lianruan_sync_runs_started_at (started_at),
  INDEX idx_ods_lianruan_sync_runs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_lianruan_raw_records (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  source_type VARCHAR(32) NOT NULL,
  resource VARCHAR(64) NOT NULL,
  source_object_id VARCHAR(191) NOT NULL,
  sync_run_id VARCHAR(96) NOT NULL,
  payload_json LONGTEXT NOT NULL,
  payload_field_names_json LONGTEXT NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  synced_at DATETIME(3) NOT NULL,
  source_updated_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_ods_lianruan_raw_source_object (source_type, resource, source_object_id),
  INDEX idx_ods_lianruan_raw_resource (resource),
  INDEX idx_ods_lianruan_raw_sync_run (sync_run_id),
  INDEX idx_ods_lianruan_raw_source_updated_at (source_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_lianruan_sync_checkpoints (
  id VARCHAR(128) NOT NULL PRIMARY KEY,
  source_type VARCHAR(32) NOT NULL,
  resource VARCHAR(64) NOT NULL,
  last_run_id VARCHAR(96) NOT NULL,
  last_synced_at DATETIME(3) NOT NULL,
  cursor_value VARCHAR(128) NULL,
  observed_total INT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_ods_lianruan_checkpoint_resource (source_type, resource)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dim_lianruan_user (
  user_id VARCHAR(128) NOT NULL PRIMARY KEY,
  username VARCHAR(128) NULL,
  user_name VARCHAR(255) NULL,
  role_code VARCHAR(64) NULL,
  role_name VARCHAR(128) NULL,
  wecom_userid VARCHAR(128) NULL,
  department_id VARCHAR(128) NULL,
  department_name VARCHAR(255) NULL,
  region VARCHAR(128) NULL,
  big_region VARCHAR(128) NULL,
  partner_id VARCHAR(128) NULL,
  partner_name VARCHAR(255) NULL,
  status VARCHAR(64) NULL,
  source_updated_at DATETIME(3) NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_dim_lianruan_user_wecom_userid (wecom_userid),
  INDEX idx_dim_lianruan_user_role_code (role_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dim_lianruan_partner (
  partner_id VARCHAR(128) NOT NULL PRIMARY KEY,
  partner_name VARCHAR(255) NULL,
  short_name VARCHAR(255) NULL,
  partner_level VARCHAR(64) NULL,
  partner_level_name VARCHAR(128) NULL,
  is_technical_service_provider TINYINT(1) NULL,
  technical_service_provider_type VARCHAR(128) NULL,
  parent_partner_id VARCHAR(128) NULL,
  region VARCHAR(128) NULL,
  big_region VARCHAR(128) NULL,
  status VARCHAR(64) NULL,
  created_at DATETIME(3) NULL,
  source_updated_at DATETIME(3) NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_dim_lianruan_partner_region (region),
  INDEX idx_dim_lianruan_partner_level (partner_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dim_lianruan_customer (
  customer_id VARCHAR(128) NOT NULL PRIMARY KEY,
  customer_name VARCHAR(255) NULL,
  customer_id_rule VARCHAR(255) NULL,
  status VARCHAR(64) NULL,
  status_name VARCHAR(128) NULL,
  category VARCHAR(64) NULL,
  category_name VARCHAR(128) NULL,
  owner_id VARCHAR(128) NULL,
  owner_name VARCHAR(255) NULL,
  assigned_staff_id VARCHAR(128) NULL,
  assigned_staff_name VARCHAR(255) NULL,
  partner_id VARCHAR(128) NULL,
  partner_name VARCHAR(255) NULL,
  region VARCHAR(128) NULL,
  big_region VARCHAR(128) NULL,
  registration_count INT NULL,
  opportunity_count INT NULL,
  quote_count INT NULL,
  order_count INT NULL,
  latest_activity_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  source_updated_at DATETIME(3) NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_dim_lianruan_customer_partner (partner_id),
  INDEX idx_dim_lianruan_customer_region (region),
  INDEX idx_dim_lianruan_customer_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fact_lianruan_registration (
  registration_id VARCHAR(128) NOT NULL PRIMARY KEY,
  customer_id VARCHAR(128) NULL,
  customer_name VARCHAR(255) NULL,
  status VARCHAR(64) NULL,
  created_by VARCHAR(128) NULL,
  created_by_name VARCHAR(255) NULL,
  assigned_staff_id VARCHAR(128) NULL,
  assigned_staff_name VARCHAR(255) NULL,
  partner_id VARCHAR(128) NULL,
  region VARCHAR(128) NULL,
  big_region VARCHAR(128) NULL,
  created_at DATETIME(3) NULL,
  source_updated_at DATETIME(3) NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_fact_lianruan_registration_customer (customer_id),
  INDEX idx_fact_lianruan_registration_partner (partner_id),
  INDEX idx_fact_lianruan_registration_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fact_lianruan_opportunity (
  opportunity_id VARCHAR(128) NOT NULL PRIMARY KEY,
  opportunity_name VARCHAR(255) NULL,
  customer_id VARCHAR(128) NULL,
  customer_name VARCHAR(255) NULL,
  stage VARCHAR(64) NULL,
  stage_name VARCHAR(128) NULL,
  status VARCHAR(64) NULL,
  amount DECIMAL(18,2) NULL,
  owner_id VARCHAR(128) NULL,
  owner_name VARCHAR(255) NULL,
  assigned_staff_id VARCHAR(128) NULL,
  assigned_staff_name VARCHAR(255) NULL,
  partner_id VARCHAR(128) NULL,
  partner_name VARCHAR(255) NULL,
  assigned_partner_id VARCHAR(128) NULL,
  region VARCHAR(128) NULL,
  big_region VARCHAR(128) NULL,
  registration_id VARCHAR(128) NULL,
  quote_id VARCHAR(128) NULL,
  expected_close_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  source_updated_at DATETIME(3) NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_fact_lianruan_opportunity_customer (customer_id),
  INDEX idx_fact_lianruan_opportunity_partner (partner_id),
  INDEX idx_fact_lianruan_opportunity_owner (owner_id),
  INDEX idx_fact_lianruan_opportunity_updated (source_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fact_lianruan_quote (
  quote_id VARCHAR(128) NOT NULL PRIMARY KEY,
  customer_id VARCHAR(128) NULL,
  customer_name VARCHAR(255) NULL,
  opportunity_id VARCHAR(128) NULL,
  partner_id VARCHAR(128) NULL,
  assigned_partner_id VARCHAR(128) NULL,
  parent_partner_id VARCHAR(128) NULL,
  assigned_staff_id VARCHAR(128) NULL,
  assigned_staff_name VARCHAR(255) NULL,
  owner_id VARCHAR(128) NULL,
  owner_name VARCHAR(255) NULL,
  amount DECIMAL(18,2) NULL,
  status VARCHAR(64) NULL,
  region VARCHAR(128) NULL,
  big_region VARCHAR(128) NULL,
  created_at DATETIME(3) NULL,
  source_updated_at DATETIME(3) NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_fact_lianruan_quote_opportunity (opportunity_id),
  INDEX idx_fact_lianruan_quote_partner (partner_id),
  INDEX idx_fact_lianruan_quote_region (region)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fact_lianruan_order (
  order_id VARCHAR(128) NOT NULL PRIMARY KEY,
  customer_id VARCHAR(128) NULL,
  customer_name VARCHAR(255) NULL,
  partner_id VARCHAR(128) NULL,
  parent_partner_id VARCHAR(128) NULL,
  assigned_partner_id VARCHAR(128) NULL,
  assigned_staff_id VARCHAR(128) NULL,
  assigned_staff_name VARCHAR(255) NULL,
  owner_id VARCHAR(128) NULL,
  owner_name VARCHAR(255) NULL,
  amount DECIMAL(18,2) NULL,
  status VARCHAR(64) NULL,
  region VARCHAR(128) NULL,
  big_region VARCHAR(128) NULL,
  deal_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  source_updated_at DATETIME(3) NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_fact_lianruan_order_partner (partner_id),
  INDEX idx_fact_lianruan_order_region (region),
  INDEX idx_fact_lianruan_order_owner (owner_id),
  INDEX idx_fact_lianruan_order_deal_at (deal_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bridge_lianruan_user_permission (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  crm_user_id VARCHAR(128) NOT NULL,
  role_code VARCHAR(64) NULL,
  scope_type VARCHAR(64) NOT NULL,
  regions_json LONGTEXT NOT NULL,
  big_regions_json LONGTEXT NOT NULL,
  partner_ids_json LONGTEXT NOT NULL,
  user_ids_json LONGTEXT NOT NULL,
  owner_ids_json LONGTEXT NOT NULL,
  managed_user_ids_json LONGTEXT NOT NULL,
  department_ids_json LONGTEXT NOT NULL,
  organization_ids_json LONGTEXT NOT NULL,
  include_child_partners TINYINT(1) NULL,
  raw_payload_json LONGTEXT NOT NULL,
  synced_at DATETIME(3) NOT NULL,
  INDEX idx_bridge_lianruan_user_permission_user (crm_user_id),
  INDEX idx_bridge_lianruan_user_permission_scope (scope_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS semantic_field_catalog (
  id VARCHAR(160) NOT NULL PRIMARY KEY,
  table_name VARCHAR(128) NOT NULL,
  field_name VARCHAR(128) NOT NULL,
  field_label VARCHAR(255) NOT NULL,
  business_meaning TEXT NULL,
  data_type VARCHAR(64) NOT NULL,
  resource VARCHAR(64) NULL,
  analysis_enabled TINYINT(1) NOT NULL DEFAULT 1,
  display_enabled TINYINT(1) NOT NULL DEFAULT 1,
  sensitive_level VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  dictionary_key VARCHAR(128) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_semantic_field_table_field (table_name, field_name),
  INDEX idx_semantic_field_resource (resource)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS semantic_metric_catalog (
  id VARCHAR(160) NOT NULL PRIMARY KEY,
  metric_key VARCHAR(128) NOT NULL UNIQUE,
  metric_label VARCHAR(255) NOT NULL,
  metric_formula TEXT NOT NULL,
  default_table VARCHAR(128) NOT NULL,
  business_meaning TEXT NULL,
  analysis_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
