export interface AccessPolicyFieldSupplement {
  allowedTables: string[];
  allowedFields: Record<string, string[]>;
}

/**
 * 读取联软标准 OpenAPI 对应的业务字段白名单补齐项。
 *
 * 参数说明：无。
 * 返回值说明：返回当前业务分析允许访问的标准资源和字段集合。
 * 调用注意事项：这里同时承接标准 OpenAPI 资源名和既有 SQL 兼容字段名，但只放入
 * P0/P1 且非敏感字段；联系人、手机号、统一社会信用代码等字段即使接口类型存在，也不得进入分析白名单。
 */
export function buildLianruanOpenApiAccessPolicySupplement(): AccessPolicyFieldSupplement {
  return {
    allowedTables: [
      'users',
      'partners',
      'registrations',
      'opportunities',
      'quotes',
      'orders',
      'customers',
      'contracts',
    ],
    allowedFields: {
      users: [
        'id',
        'username',
        'name',
        'role',
        'roleName',
        'region',
        'bigRegion',
        'partnerId',
        'partnerName',
        'status',
        'wecomUserId',
        'departmentId',
        'departmentName',
      ],
      partners: [
        'id',
        'partnerId',
        'name',
        'partnerName',
        'displayName',
        'shortName',
        'partnerLevel',
        'partnerLevelName',
        'level',
        // 合作级别（LEP/金牌/银牌/钻石），与渠道等级是不同维度
        'cooperationLevel',
        'cooperationLevelName',
        'partnerType',
        'partnerTypeName',
        'isTechnicalServiceProvider',
        'technicalServiceProviderType',
        'isTechService',
        'techServiceType',
        'region',
        'bigRegion',
        'status',
        'parentPartnerId',
        'parentPartnerIds',
        'joinDate',
        'quoteCount',
        'orderCount',
        'totalAmt',
        'totalAmount',
        'createdAt',
        'updatedAt',
      ],
      registrations: [
        'id',
        'registrationId',
        'customerId',
        'customerIdRule',
        'customer',
        'customerName',
        'status',
        'statusName',
        'ownerId',
        'ownerName',
        'createdBy',
        'createdByName',
        'assignedStaffId',
        'assignedStaffName',
        'partnerId',
        'partnerName',
        'assignedPartnerId',
        'assignedPartnerName',
        'opportunityId',
        'opportunityName',
        'region',
        'bigRegion',
        'createdAt',
        'updatedAt',
        'approvedAt',
        'expireAt',
      ],
      opportunities: [
        'id',
        'opportunityId',
        'name',
        'opportunityName',
        'title',
        'customerId',
        'customerIdRule',
        'customer',
        'customerName',
        'registrationId',
        'stage',
        'stageName',
        'status',
        'statusName',
        'amount',
        'opportunityAmount',
        'opportunity_amount',
        'expectedAmount',
        'expectedClose',
        'expectAmount',
        'expect_amount',
        'estimatedAmt',
        'estimatedAmount',
        'createdBy',
        'createdByName',
        'ownerId',
        'ownerName',
        'assignedStaffId',
        'assignedStaffName',
        'partnerId',
        'partnerName',
        'assignedPartnerId',
        'assignedPartnerName',
        'partner_id',
        'region',
        'bigRegion',
        'regId',
        'quoteId',
        'sourceUpdatedAt',
        'latestFollowUpAt',
        'lastProgressAt',
        'progressUpdatedAt',
        'createdAt',
        'created_at',
        'updatedAt',
      ],
      quotes: [
        'id',
        'quoteId',
        'quoteName',
        'customerId',
        'customerIdRule',
        'customer',
        'customerName',
        'registrationId',
        'regId',
        'opportunityId',
        'opportunityIds',
        'opportunityName',
        'oppId',
        'oppIds',
        'partnerId',
        'partnerName',
        'assignedPartnerId',
        'assignedPartnerName',
        'parentPartnerId',
        'amount',
        'total',
        'totalAmount',
        'originalTotal',
        'discountAmount',
        'ownerId',
        'ownerName',
        'assignedStaffId',
        'assignedStaffName',
        'createdBy',
        'createdByName',
        'status',
        'region',
        'bigRegion',
        'createdAt',
        'updatedAt',
      ],
      orders: [
        'id',
        'orderId',
        'orderNo',
        'orderName',
        'customerId',
        'customerIdRule',
        'customer',
        'customerName',
        'registrationId',
        'regId',
        'opportunityId',
        'opportunityName',
        'quoteId',
        'partnerId',
        'partnerName',
        'assignedPartnerId',
        'assignedPartnerName',
        'parentPartnerId',
        'amount',
        'total',
        'totalAmount',
        'ownerId',
        'ownerName',
        'assignedStaffId',
        'assignedStaffName',
        'createdBy',
        'createdByName',
        'status',
        'statusName',
        'orderAmount',
        'order_amount',
        'region',
        'bigRegion',
        'createdAt',
        'dealAt',
        'completedAt',
        'updatedAt',
      ],
      customers: [
        'id',
        'customerId',
        'name',
        'customer',
        'createdAt',
        'updatedAt',
        'latestActivityAt',
        'status',
        'statusName',
        'region',
        'bigRegion',
        'ownerId',
        'ownerName',
        'assignedStaffId',
        'assignedStaffName',
        'partnerId',
        'partnerName',
        'departmentId',
        'departmentName',
        'organizationId',
        'source',
        'category',
        'categoryName',
        'hasRegistration',
        'registrationCount',
        'hasOpportunity',
        'opportunityCount',
        'hasQuote',
        'quoteCount',
        'hasOrder',
        'orderCount',
        'ageBucket',
        'customerIdRule',
        'matchKey',
        'organization_id',
        'department_id',
        'user_id',
        'created_at',
      ],
      contracts: [
        'id',
        'title',
        'status',
        'organization_id',
        'department_id',
        'user_id',
        'partner_id',
        'total_amount',
        'unreceived_amount',
        'sign_date',
        'created_at',
        'approve_status',
        'pending_step',
        'submit_applying_at',
        'finish_approve_at',
      ],
    },
  };
}

/**
 * 合并默认白名单与联软标准字段补齐项。
 *
 * 参数说明：
 * - `basePolicy`：当前默认访问策略中的表和字段配置。
 * 返回值说明：返回去重后的表与字段配置。
 * 调用注意事项：只追加缺失项，不删除既有字段，避免影响历史模板和管理员已配置能力。
 */
export function mergeLianruanOpenApiAccessPolicySupplement(basePolicy: {
  allowedTables: string[];
  allowedFields: Record<string, string[]>;
}): {
  allowedTables: string[];
  allowedFields: Record<string, string[]>;
} {
  const supplement = buildLianruanOpenApiAccessPolicySupplement();
  const allowedTables = Array.from(
    new Set([...basePolicy.allowedTables, ...supplement.allowedTables]),
  );
  const tableNames = new Set([
    ...Object.keys(basePolicy.allowedFields),
    ...Object.keys(supplement.allowedFields),
  ]);
  const allowedFields = Object.fromEntries(
    [...tableNames].map((tableName) => [
      tableName,
      Array.from(
        new Set([
          ...(basePolicy.allowedFields[tableName] ?? []),
          ...(supplement.allowedFields[tableName] ?? []),
        ]),
      ),
    ]),
  );

  return { allowedTables, allowedFields };
}
